### ISSUE TITLE
start does not seem to work correctly

### ISSUE THREAD

**Issue by crlaugh** [ModiaSim/TinyModia.jl#7]
I am trying to get a first-order ODE working in which I initialize the state variable at a nonzero value, but neither setting start=1.0 or init=1.0 seems to change the result.  My code is as follows: 
```
using TinyModia
using ModiaBase
using ModiaPlot

Var(args...; kwargs...) = (;args..., kwargs...)
Var(value::Union{Float64, Int64, Bool, String, Expr}, args...; kwargs...) = (;value = value, args..., kwargs...)

SimpleModel = Model(
    T = 1.0,
    x = Var(start=1.0),
    equation = :[T * der(x) + x = 0.0],
)

simpleModel = @instantiateModel(SimpleModel)
simulate!(simpleModel, stopTime=10.0)
plot(simpleModel, "x", figure=1)
```
The result is fixed at zero, e.g., 
![image](https://user-images.githubusercontent.com/9616147/120360716-0efab280-c2d7-11eb-94fc-97b7635e29f6.png)

Is this a bug, or is some method other than what I included here needed?

**Comment by HildingElmqvist** [comment]
Var is predefined and init should be used.

I changed the model to:
`module TestLaughman

using TinyModia
using ModiaBase
using ModiaPlot

SimpleModel = Model(
    T = 1.0,
    x = Var(init=1.0),
    equation = :[T * der(x) + x = 0.0],
)

simpleModel = @instantiateModel(SimpleModel)
simulate!(simpleModel, stopTime=10.0)
plot(simpleModel, "x", figure=1)

end`

and it worked. 

Are you using an old version of TinyModia?

**Comment by crlaugh** [comment]
Thanks for the quick turnaround!  I was using 0.7, which is the version installed with `] up TinyModia`.  However, forcing version 0.7.2 via `]add TinyModia@v0.7.2` solved the problem.
